
import React from 'react';
import { AdobeCategory } from './types';

export const ADOBE_CATEGORIES: AdobeCategory[] = [
  { id: 1, name: 'Animals' }, { id: 2, name: 'Buildings and Architecture' }, { id: 3, name: 'Business' },
  { id: 4, name: 'Drinks' }, { id: 5, name: 'The Environment' }, { id: 6, name: 'States of Mind' },
  { id: 7, name: 'Food' }, { id: 8, name: 'Graphic Resources' }, { id: 9, name: 'Hobbies and Leisure' },
  { id: 10, name: 'Industry' }, { id: 11, name: 'Landscapes' }, { id: 12, name: 'Lifestyle' },
  { id: 13, name: 'People' }, { id: 14, name: 'Plants and Flowers' }, { id: 15, name: 'Culture and Religion' },
  { id: 16, name: 'Science' }, { id: 17, name: 'Social Issues' }, { id: 18, name: 'Sports' },
  { id: 19, name: 'Technology' }, { id: 20, name: 'Transport' }, { id: 21, name: 'Travel' }
];

export const SHUTTERSTOCK_CATEGORIES = [
  'Abstract', 'Animals/Wildlife', 'Backgrounds/Textures', 'Beauty/Fashion', 
  'Buildings/Landmarks', 'Business/Finance', 'Education', 'Food and Drink', 
  'Healthcare/Medical', 'Holidays', 'Industrial', 'Interiors', 'Miscellaneous', 
  'Nature', 'Objects', 'Parks/Outdoor', 'People', 'Religion', 'Science', 
  'Signs/Symbols', 'Sports/Recreation', 'Technology', 'Transportation', 'Vintage'
];

export const SHUTTERSTOCK_CATEGORIES_VIDEO = [
  'Animals/Wildlife', 'Backgrounds/Textures', 'Buildings/Landmarks',
  'Business/Finance', 'Education', 'Food and Drink', 'Healthcare/Medical',
  'Holidays', 'Industrial', 'Nature', 'Objects', 'People', 'Religion',
  'Science', 'Signs/Symbols', 'Sports/Recreation', 'Technology', 'Transportation'
];

export type AppLanguage = 'en' | 'id';

export const getDailyLimit = (): number => {
  return 25;
};

export const TRANSLATIONS = {
  en: {
    header_title: "MetaZo PRO",
    main_subtitle_line1: "AI-Powered Metadata Assistant",
    main_subtitle_line2: "Specializing in Adobe Stock, Shutterstock, Freepik, Vecteezy, Canva Contributors",
    
    help_button: "WhatsApp Group & Support",
    donate_button: "Donate / Support",
    whatsapp_link: "https://chat.whatsapp.com/EJgcCSymQYE3724FqpFzxr", 
    footer_text: "🔐 Developed with dedication @2026.",

    image_tool: "Image",
    video_tool: "Video",
    vector_tool: "Vector",
    
    upload_images: "1. Upload Image Files",
    upload_videos: "1. Upload Video Files",
    upload_vector_thumbnails: "1. Upload Vector Files",
    drag_drop: "Drag & drop here, or",
    click_to_choose: "choose files",
    files_selected: "files selected.",
    uploading_file: "Processing upload...",
    add_new: "Add More",
    clear_all: "Clear All",

    generate_metadata_ai: "2. AI Metadata Optimization",
    generate_desc: "AI analyzes visual content (including multi-frame for video) for the best results.",
    continue_generate: "Continue Process",
    custom_prompt_optional: "Instructions / Target Keywords (Optional):",
    custom_prompt_placeholder: "Example: 'retro style, focus on red scarf' or 'Blue, Ocean, Summer'.",
    keyword_count_label: "Keyword Count (1-49):",
    keyword_count_auto: "Auto",
    generate_all: "Process Metadata",
    generating: "AI is analyzing...",
    retry_failed: "Retry Failed",
    ai_processing: "AI processing in progress...",
    generation_mode_label: "Processing Mode:",
    generation_mode_standard: "Standard",
    generation_mode_standard_desc: "Accurate, stable.",
    generation_mode_batch: "Batch",
    generation_mode_batch_desc: "Fast, simultaneous processing.",

    review_edit: "3. Review & Refine",
    review_edit_desc: "Verify compliance with stock standards through the preview box.",
    keywords_label: "Keywords",
    title_label: "Title",
    description_label: "Description",
    category_adobe_label: "Adobe Stock Category",
    category_shutterstock_1_label: "Shutterstock Category 1",
    category_shutterstock_2_label: "Shutterstock Category 2",
    enter_title: "Enter title...",
    enter_description: "Describe content...",
    select_category: "Select category...",
    original_filename: "Filename:",
    close: "Close",
    download_csv: "Download CSV",
    download_disabled_tooltip: "Complete all AI processes first.",
    export_metadata: "4. Export",
    language: "Language",
    english: "English",
    indonesian: "Indonesian",
    regenerate: "Regenerate Metadata",
    hero_badge: "AI-Driven Metadata Engine",
    hero_title_part1: "Instant",
    hero_title_part2: "Stock Asset",
    hero_title_part3: "Optimization",
    hero_description: "MetaZo leverages AI intelligence to generate titles, descriptions, and tags automatically for global stock portals.",
    hero_cta_how: "How to Use",
    hero_stats_file: "Files",
    license_active_title: "Commercial License Active",
    license_active_desc: "Unlimited access is active for professional workflow",
    license_pro_badge: "★ PRO",
    trial_badge: "Trial Version",
    trial_desc_part1: "Use",
    trial_desc_part2: "in limited mode. Get unlimited access with a premium license for",
    trial_cta_license: "License",
    trial_cta_admin: "Admin",
    workspace_title: "Choose Your Workspace",
    workspace_modes: "3 Modes",
    image_ws_title: "Image AI",
    image_ws_desc: "Automatically optimize photos, posters, or raster artwork (JPG, PNG, WEBP).",
    image_ws_cta: "Optimize Images",
    video_ws_title: "Video AI",
    video_ws_desc: "Analyze video clips (MP4, MOV, WEBM) for precise cinematic metadata.",
    video_ws_cta: "Optimize Videos",
    vector_ws_title: "Vector AI",
    vector_ws_desc: "Automatic metadata for vector files (SVG, EPS, AI) for UI/UX design needs.",
    vector_ws_cta: "Optimize Vectors",
    daily_quota: "Daily Quota",
    quota_exhausted: "⚠️ Quota exhausted. Try tomorrow.",
    queue_status_title: "Data Queue Status",
    status_success: "Metadata OK",
    status_ready: "Ready for AI",
    status_draft: "Unconfigured Draft",
    status_error: "Issue / Error",
    success_rate: "Success Rate",
    dist_title: "Upload Format Distribution",
    no_files_title: "No Files Uploaded Yet",
    no_files_desc: "Use the \"Metadata Gen\" menu tab to upload your files.",
    dist_image_label: "Image Workspace",
    dist_video_label: "Video Workspace",
    dist_vector_label: "Vector Workspace",
    portal_ready: "Ready",
    sidebar_dashboard: "Dashboard",
    sidebar_metadata_gen: "Metadata Gen",
    sidebar_prompt_gen: "Prompt Gen",
    sidebar_prompt_text: "Text Prompt",
    sidebar_prompt_image: "Image Prompt",
    sidebar_prompt_video: "Video Prompt",
    sidebar_image_check: "Image Check",
    sidebar_video_check: "Video Quality Check",
    sidebar_calendar_gen: "Calendar Gen",
    sidebar_ftp_uploader: "FTP Stock Uploader",
    sidebar_chat: "Account Chat",
    sidebar_activation_premium: "ACTIVATE PREMIUM",
    sidebar_pro_active: "PRO ACTIVE",
    sidebar_manage: "Manage",
    sidebar_core_generators: "Core Generators",
    sidebar_core_tools: "Core Tools",
    sidebar_processing_mode: "Processing Mode",
    sidebar_tuning: "Tuning",
    sidebar_resources: "Resources",
    sidebar_about: "About MetaZo PRO",
    sidebar_subscription_plan: "Subscription Plan",
    default_pricing: "30 Days = $2 - Unlimited = $14",
    topbar_system_time: "Current System Time",
    topbar_stability_core: "STABILITY CORE ONLINE",
    topbar_pro_active: "👑 PRO ACTIVE",
    topbar_trial_eval: "⚠️ TRIAL EVAL",
    upload_title: "Upload Assets",
    upload_reset: "Reset",
    upload_reset_title: "Reset Everything",
    upload_help: "Upload your image, video, or vector files here to process.",
    upload_file_placeholder: "FILE",
    upload_next_ai: "Next: AI Config",
    info_modal_title: "MetaZo PRO Handbook & Usage Guide",
    info_modal_operational_guide: "✨ MetaZo PRO Operational Guide",
    info_modal_step1_title: "Workspace Selection",
    info_modal_step1_desc_p1: "Choose mode",
    info_modal_step1_desc_p2: "on the main Dashboard. Upload your files via drag-and-drop or by clicking the upload area.",
    info_modal_step2_title: "AI Analysis & Metadata Generation",
    info_modal_step2_desc: "Once uploaded, click Process Metadata. Our AI Vision engine will analyze the visual content to generate Titles, Descriptions, and Categories automatically.",
    info_modal_step3_title: "Prompt Gen & Image AI (Integrated!)",
    info_modal_step3_desc_highlight: "The Prompt Gen feature is now integrated with Calendar Gen to make it easier to create stock content based on popular events.",
    info_modal_step3_desc_main: "Use the Prompt Gen feature to generate in-depth visual descriptions for AI Art.",
    info_modal_step4_title: "Image Check (QC)",
    info_modal_step4_desc: "Ensure your assets are free from IP violations, logos, and excessive noise with the Image Check feature before uploading to agencies.",
    info_modal_step5_title: "Calendar Gen (Niche Hunter)",
    info_modal_step5_desc: "Find important future global events to help you determine the themes for stock content production that buyers are searching for.",
    info_modal_step6_title: "Export & Download",
    info_modal_step6_desc: "Once satisfied, use the Export feature to download metadata in CSV format compatible with Adobe Stock, Shutterstock, etc.",
    info_modal_tips_title: "⚡ Processing Mode Tips",
    info_modal_std_mode_title: "Standard Mode",
    info_modal_std_mode_desc: "Processes files one by one in sequence. Very safe and stable to avoid API rate limit issues.",
    info_modal_batch_mode_title: "Batch Mode",
    info_modal_batch_mode_desc: "Processes many files simultaneously. Recommended for processing large quantities of assets if time is your main priority.",
    info_modal_trial_premium_title: "💳 Trial & Premium Handbook",
    info_modal_trial_mode_label: "Trial Mode:",
    info_modal_trial_mode_desc: "You are in a free trial period with daily limits to ensure system stability. Certain features may be limited.",
    info_modal_premium_mode_label: "Premium (License):",
    info_modal_premium_mode_desc: "With a license Serial Key, all limits are completely removed. Get unlimited access for your professional asset processing.",
    info_modal_license_cta: "Need a license? Contact admin to get an official Serial Key & upgrade your account to Premium!",
    info_modal_supported_formats: "📁 Supported File Formats",
    info_modal_close_button: "Close Guide",
    settings_modal_title: "AI Model Provider Settings",
    settings_main_provider_label: "Main AI Provider Used",
    settings_gemini_model_label: "Select Gemini Model",
    settings_gemini_desc: "You can save several personal Gemini API Keys. The system intelligently performs automatic rotation to avoid quota issues (*rate limit / RESOURCE_EXHAUSTED*).",
    settings_gemini_key_list: "Gemini API Key List",
    settings_no_keys: "No API Keys found matching this provider.",
    settings_gemini_model_auto: "Automatic (Auto-Select Reliable)",
    settings_use_default_key: "Using global server default Gemini Key.",
    welcome_title: "Welcome to MetaZo PRO v1.3.0",
    welcome_subtitle: "Stock Asset Optimizer",
    welcome_features_label: "Features:",
    welcome_feature1: "AI-powered stock asset optimization",
    welcome_feature2: "Lightweight & fast generation",
    welcome_feature3: "Multiple provider support",
    welcome_feature4: "Advanced prompt management",
    welcome_get_started: "Get Started",
    common_or: "or",
    common_and: "and",
    activation_modal_title_trial_expired: "Trial Expired",
    activation_modal_title_normal: "Official License Activation",
    activation_modal_unlock_premium: "Unlock Premium SaaS",
    activation_active_status: "Application Active • Premium PRO",
    activation_key_registered: "Registered Key:",
    activation_subscription_left: "Subscription Period:",
    activation_days_left: "Days Left",
    activation_commercial_notice: "Commercial copy licensed under key constraints.",
    activation_btn_unsubscribe: "Unsubscribe (Revoke License)",
    activation_trial_expired_hero: "7-Day Trial Expired!",
    activation_trial_expired_desc: "Your free trial has ended. Please make a payment and enter the License Serial Key below to continue using Metadata Gen, Prompt Text, & Calendar Gen.",
    activation_trial_active_hero: "Trial Mode Active",
    activation_trial_active_days: "Days Left",
    activation_trial_active_desc: `You are in Free Trial mode. All features are unlocked with a limit of ${getDailyLimit()} generations per day. Activate officially to unlock unlimited generations.`,
    activation_input_label: "Enter License Serial Key",
    activation_input_placeholder: "FORMAT: MZPRO-XXXX-XXXX-XXXX",
    activation_error_empty: "Please enter your license Serial Key first.",
    activation_error_expired: "This Serial Key (30 Days) has expired. Please buy a new key.",
    activation_error_used: "This Serial Key is already used by another user! Please use a different Serial Key.",
    activation_error_invalid: "Serial Key not registered or incorrect. Please contact Admin to buy an Official Key.",
    activation_error_offline: "Internet connection issue and offline validation failed.",
    activation_success_waiting: "✔ License validated! Enabling premium...",
    activation_btn_process: "Processing Activation...",
    activation_btn_activate: "Activate Premium",
    activation_no_license_title: "Don't have a License? Get it Instant:",
    activation_personal_activation: "Personal Activation",
    activation_license_price: "License Price:",
    activation_buy_whatsapp: "Buy License Key via WhatsApp",
    activation_confirm_stop_title: "Cancellation Confirmation",
    activation_confirm_stop_desc: "Are you sure you want to turn off premium status and return the application to trial mode?",
    activation_btn_stop_yes: "Yes, Stop",
    activation_btn_stop_no: "Cancel",
    sidebar_expand: "Expand Sidebar",
    sidebar_collapse: "Collapse Sidebar",
    sidebar_manage_license: "Manage License / Unsubscribe",
    sidebar_activation_tooltip: "Activate Official License / Start Pro",
    topbar_toggle_theme: "Toggle Theme",
    topbar_info_manual: "Information Manual",
    topbar_settings_api: "Settings & API Key",
    common_editor: "Editor",
    common_mode: "Mode",
    prompt_title: "Prompt Text Studio",
    prompt_subtitle: "Synthesize Visual Ideas with a Spectrum of Creativity & Artistic Categories",
    prompt_engine_active: "Gemini Pro Engine Active",
    prompt_formula_title: "Artistic Formula & Configuration",
    prompt_tab_background: "Tab Background",
    prompt_tab_png: "Tab PNG Asset",
    prompt_trial_label: "Today's Trial: Prompt Text",
    prompt_generate_count: "Generates",
    prompt_trial_expired: `⚠️ Daily free trial limit (${getDailyLimit()} generates) reached. Please contact admin or enter activation code for unlimited processing.`,
    prompt_trial_remaining: `Free trial ${getDailyLimit()} generates/day. Remaining quota today:`,
    prompt_trial_times: "times",
    prompt_image_trial_label: "Today's Trial: Prompt Image",
    prompt_image_generate_count: "Generates",
    prompt_image_trial_expired: `⚠️ Daily free trial limit (${getDailyLimit()} generates) reached. Please contact admin or enter activation code for unlimited processing.`,
    prompt_image_trial_remaining: `Free trial ${getDailyLimit()} generates/day. Remaining quota today:`,
    prompt_image_trial_times: "times",
    prompt_video_trial_label: "Today's Trial: Prompt Video",
    prompt_video_generate_count: "Generates",
    prompt_video_trial_expired: `⚠️ Daily free trial limit (${getDailyLimit()} generates) reached. Please contact admin or enter activation code for unlimited processing.`,
    prompt_video_trial_remaining: `Free trial ${getDailyLimit()} generates/day. Remaining quota today:`,
    prompt_video_trial_times: "times",
    image_check_trial_label: "Today's Trial: Image Quality Audit",
    image_check_generate_count: "Audits",
    image_check_trial_expired: `⚠️ Daily free trial limit (${getDailyLimit()} audits) reached. Please contact admin or enter activation code for unlimited processing.`,
    image_check_trial_remaining: `Free trial ${getDailyLimit()} audits/day. Remaining quota today:`,
    image_check_trial_times: "times",
    prompt_subject_label: "Visual Idea / Image Subject",
    prompt_subject_placeholder: "Type your visual idea freely here...",
    prompt_inspiration_label: "💡 Need Inspiration? Click Presets below:",
    prompt_negative_label: "Negative Prompt (Anti-Elements)",
    prompt_negative_subtitle: "Avoid Elements",
    prompt_negative_desc: "The above elements will be strictly sent to the AI model to be avoided in the prompt synthesis.",
    prompt_style_master_label: "Artistic Master Style Category",
    prompt_style_quick_label: "Quick Selection Tab",
    prompt_png_bg_label: "PNG Background Options",
    prompt_png_bg_desc: "The AI will smartly embed this background color instruction into the prompt to neatly isolate the image subject.",
    prompt_variation_label: "Dimension & Output Variation Count",
    prompt_variation_unit: "Variations",
    prompt_word_count_label: "Word Count Range (Prompt Length)",
    prompt_word_count_desc: "Adjusts how detailed the AI expands the visual description of each prompt.",
    prompt_btn_synthesize: "Synthesize {count} Prompts Now",
    prompt_btn_synthesizing: "AI Expanding {count} Artistic Variations...",
    prompt_preset_lite: "Fast, efficient, concise and representative formulation.",
    prompt_preset_artistic: "Full of camera options, varied lenses, and balanced aesthetic style.",
    prompt_preset_ultra: "Super complex details, rich textures, lighting options, and variety of perspectives.",
    prompt_loading_step1: "Formulating Creative Scenarios...",
    prompt_loading_step2: "Synthesizing Artistic Detail...",
    prompt_loading_step3: "Polishing Prompt Spectrum...",
    prompt_loading_step4: "Finalizing Output Collection...",
    prompt_studio_title: "Prompt Text Studio",
    prompt_studio_subtitle: "Synthesize Visual Ideas with a Spectrum of Creativity & Artistic Categories",
    prompt_studio_version: "Advanced AI Text Creator v2.5",
    prompt_output_title: "Generated Prompts",
    prompt_output_subtitle: "All prompts are ready to be copied to Midjourney / DALL-E / Firefly / Stable Diffusion",
    prompt_output_badge_png: "✨ PNG: BACKGROUND {color}",
    prompt_output_badge_scene: "🖼️ Background Scene",
    prompt_output_btn_copy_all: "Copy All",
    prompt_output_btn_copied: "Copied",
    prompt_output_btn_download: "Download",
    prompt_output_btn_clear: "Clear",
    prompt_output_search_placeholder: "Filter prompts (e.g.: 'lighting', 'macro', 'epic', 'camera')...",
    prompt_output_no_match_title: "No filter matches",
    prompt_output_no_match_desc: "Keyword \"{query}\" not found in {count} prompts.",
    image_studio_title: "Prompt Image Studio",
    image_studio_subtitle: "Extract Description & Aesthetics from Your Image Reference (Single & Batch Mode)",
    image_studio_version: "Image-to-Prompt Batch v2.0",
    image_studio_upload_label: "Image Upload Panel",
    image_studio_clear_all: "Clear All",
    image_studio_drag_drop: "Upload / Drag Images",
    image_studio_release: "Release Images",
    image_studio_support_multiple: "Supports multiple files at once",
    image_studio_target_label: "Select Aesthetic Target",
    image_studio_btn_analyze: "Generate Prompt ({count} New Items)",
    image_studio_btn_analyzing: "Processing {count} Items ({progress}%)",
    image_studio_dashboard_title: "Queue Progress Dashboard",
    image_studio_status_label: "Status: {finished}/{total} Finished",
    image_studio_btn_copy_all: "Copy All",
    image_studio_btn_copied_all: "Copied All",
    image_studio_empty_title: "No Images in Queue Yet",
    image_studio_empty_desc: "Upload one or more reference images to instantly extract AI aesthetic prompts.",
    
    video_studio_title: "Prompt Video Studio",
    video_studio_subtitle: "Synthesize Descriptions & Prompts from Video Motion References",
    video_studio_keyword_placeholder: "Enter motion keyword (e.g., 'Cinematic Landscape', 'Epic Action')...",
    video_studio_btn_analyze: "Analyze Motion",
    video_studio_btn_analyzing: "Analyzing...",
    video_studio_history_title: "Analysis History",
    video_studio_btn_clear_history: "Clear History",
    video_studio_hollywood_title: "Hollywood Synthesis",
    video_studio_hollywood_desc: "Generate professional Hollywood-standard director prompts based on motion analysis.",
    video_studio_btn_generate_hollywood: "Generate Hollywood Prompts",
    video_studio_btn_generating_hollywood: "Synthesizing Hollywood Prompts...",
    video_studio_btn_download: "Download Prompts",
    video_studio_camera_label: "Camera",
    video_studio_technical_label: "Technical String",
    video_studio_saturation_title: "Market Saturation Alert",
    video_studio_saturation_desc: "Automatic warning if the market is too saturated with similar content.",
    video_studio_revenue_title: "Revenue Forecast",
    video_studio_revenue_desc: "Estimated revenue potential based on buyer trends at Adobe Stock & Shutterstock.",
    video_studio_error_empty: "Please enter a keyword first.",
    video_studio_error_fail: "Failed to analyze keyword. Try again later.",
    calendar_title: "Visual Calendar Planner",
    calendar_subtitle: "Find strategic moments based on holidays & global market trends.",
    calendar_months_january: "January",
    calendar_months_february: "February",
    calendar_months_march: "March",
    calendar_months_april: "April",
    calendar_months_may: "May",
    calendar_months_june: "June",
    calendar_months_july: "July",
    calendar_months_august: "August",
    calendar_months_september: "September",
    calendar_months_october: "October",
    calendar_months_november: "November",
    calendar_months_december: "December",
    calendar_btn_generate: "Find Events",
    calendar_btn_generating: "Analyzing...",
    calendar_month_label: "Select Month",
    calendar_card_btn_keywords: "Generate Keywords",
    calendar_card_btn_prompt: "Create Prompt",
    calendar_error_fail: "Failed to generate events. Please try again.",
    
    style_photorealistic: "Photorealistic (Realistic)",
    style_cinematic: "Cinematic (Film)",
    style_adobe_stock: "Adobe Stock Style",
    style_editorial: "Editorial (Magazine)",
    style_lifestyle: "Lifestyle (Life Style)",
    style_fine_art: "Fine Art (High Art)",
    prompt_error_trial: `Trial Limit Exceeded. You have reached the maximum limit of ${getDailyLimit()} Prompt Text generates today. Please contact admin or enter activation code for unlimited processing.`,
    prompt_error_empty: "Please enter a base idea or pure visual subject first.",
    prompt_png_bg_white: "⚪ White background",
    prompt_png_bg_black: "⚫ Black background",
    prompt_png_bg_transparent: "🏁 Transparent background",
    qc_title: "Quality",
    qc_title_check: "Check",
    qc_subtitle: "AI Expert for Adobe Stock Standards",
    qc_btn_reset: "Reset",
    qc_btn_analyze: "Start Audit Asset",
    qc_btn_analyzing: "Analyzing...",
    qc_tolerance_label: "Quality Tolerance",
    qc_upload_hub: "Upload Hub",
    qc_drop_images_here: "Drop Images/Video/Vector Here",
    qc_release_images: "Release Files",
    qc_multiple_upload: "Supports Images, Videos & Vectors (.eps, .ai)",
    qc_queue_assets: "Assets in Queue",
    qc_pending_audit: "Pending Audit",
    qc_analyzing_text: "Adobe Stock QC Specialist",
    qc_analyzing_desc: "Analyzing legal, technical, and commercial value",
    qc_info_empty: "Please upload files first to start the curation audit process",
    qc_score_label: "QC SCORE",
    qc_hide_heatmap: "Hide Heatmap",
    qc_analyze_heatmap: "Analyze Pixel Heatmap",
    qc_pixel_engine: "Pixel Engine",
    qc_rejection_reason: "Rejection Reason",
    qc_legal_status: "Legal Status",
    qc_quality_metadata: "Quality Metadata",
    qc_close: "Close",
    qc_view_audit: "View Audit",
    qc_strengths: "Strengths",
    qc_tech_analysis: "Technical Analysis",
    qc_detailed_feedback: "Detailed Feedback",
    
    guide_btn_title: "View Feature Guide",
    guide_dashboard_title: "Dashboard Guide",
    guide_dashboard_desc: "Overview of your account health, generation statistics, and application links.",
    guide_prompt_gen_title: "Prompt Studio Guide",
    guide_prompt_gen_desc: "The Prompt Text feature helps you craft high-converting, professional prompt formulas for modern GenAI models (Midjourney, DALL-E 3, Stable Diffusion, Recraft, Flux, etc.).\n\n📌 Complete Prompt Text Guide:\n\n1. 📝 Subject Input & Auto Subject Idea:\n• Type any keyword, concept, or subject (e.g. \"cyberpunk barista robot\", \"cozy winter coffee shop\").\n• Out of ideas? Click the \"✨ Auto Subject\" button to automatically generate fresh, high-demand commercial concepts.\n\n2. 🎭 Output Mode (Full Background vs Isolated PNG):\n• Full Background Mode: Generates complete environments, landscapes, wallpapers, or full scene compositions.\n• Isolated PNG Mode: Generates standalone subjects isolated against solid backgrounds (White / Black / Transparent) ready for cutout elements and stock design assets.\n\n3. 🎨 Visual Style Presets & Sub-Styles:\n• Choose from 20+ curated visual styles (Flat Illustration, 3D CGI, Cinematic, Photorealistic, Vector Art, Watercolor, Cyberpunk, Anime, Graphic Design, etc.).\n• For specific categories like Flat Vector or Dark Horror, customize granular sub-styles such as Minimal Flat, Corporate Alegria, Isometric, or Gothic Horror.\n\n4. ⚙️ Number of Variations & Negative Prompt:\n• Variation Slider (5 - 15): Choose how many distinct, creative prompt variations to generate at once.\n• Negative Prompt: Specify unwanted attributes to exclude from generated images (e.g. \"blurry, text, watermark, bad anatomy\").\n\n5. 📋 Copy & Export:\n• Copy individual prompt cards with one click, or use \"Copy All\" to copy the entire variation batch directly to your clipboard.",
    guide_prompt_text_title: "Prompt Text Guide",
    guide_prompt_text_desc: "The Prompt Text feature helps you craft high-converting, professional prompt formulas for modern GenAI models (Midjourney, DALL-E 3, Stable Diffusion, Recraft, Flux, etc.).\n\n📌 Complete Prompt Text Guide:\n\n1. 📝 Subject Input & Auto Subject Idea:\n• Type any keyword, concept, or subject (e.g. \"cyberpunk barista robot\", \"cozy winter coffee shop\").\n• Out of ideas? Click the \"✨ Auto Subject\" button to automatically generate fresh, high-demand commercial concepts.\n\n2. 🎭 Output Mode (Full Background vs Isolated PNG):\n• Full Background Mode: Generates complete environments, landscapes, wallpapers, or full scene compositions.\n• Isolated PNG Mode: Generates standalone subjects isolated against solid backgrounds (White / Black / Transparent) ready for cutout elements and stock design assets.\n\n3. 🎨 Visual Style Presets & Sub-Styles:\n• Choose from 20+ curated visual styles (Flat Illustration, 3D CGI, Cinematic, Photorealistic, Vector Art, Watercolor, Cyberpunk, Anime, Graphic Design, etc.).\n• For specific categories like Flat Vector or Dark Horror, customize granular sub-styles such as Minimal Flat, Corporate Alegria, Isometric, or Gothic Horror.\n\n4. ⚙️ Number of Variations & Negative Prompt:\n• Variation Slider (5 - 15): Choose how many distinct, creative prompt variations to generate at once.\n• Negative Prompt: Specify unwanted attributes to exclude from generated images (e.g. \"blurry, text, watermark, bad anatomy\").\n\n5. 📋 Copy & Export:\n• Copy individual prompt cards with one click, or use \"Copy All\" to copy the entire variation batch directly to your clipboard.",
    guide_prompt_image_title: "Prompt Image Guide",
    guide_prompt_image_desc: "Upload reference images to extract descriptions and aesthetic details for generating new prompt formulas.\n\n📌 Prompt Image Guide:\n1. Paste Button (Ctrl+V):\n• Copy an image from anywhere (right-click > Copy Image) or take a screenshot (Win + Shift + S), then click the \"Salin Tempel (Ctrl+V)\" button or press Ctrl+V to process immediately without downloading files first.\n\n2. Number of Prompt Variations:\n• Adjust the slider (5 - 15 variations) to determine how many unique prompt variations you want to generate from a single reference image.\n\n3. \"Without Style\" (Tanpa Style) Option:\n• Enable the \"Tanpa Style\" checkbox so AI automatically adapts to the original medium & aesthetic style of the reference image without applying preset styles.",
    guide_prompt_video_title: "Prompt Video Guide",
    guide_prompt_video_desc: "Analyze motion keywords to synthesize professional cinematic director prompts and evaluate market potential.",
    guide_image_title: "Image AI Guide",
    guide_image_desc: "Upload images to automatically generate Adobe/Shutterstock optimized metadata including standard Title, Description, and Keywords.",
    guide_video_title: "Video AI Guide",
    guide_video_desc: "Upload videos to get precise metadata specifically focused on motion, action, speed, and cinematic keywords.",
    guide_vector_title: "Vector EPS Guide",
    guide_vector_desc: "Upload large EPS files. The system will safely auto-convert EPS into previews and extract intelligent metadata.",
    guide_image_check_title: "Quality Check Guide",
    guide_image_check_desc: "The Quality Check feature scans and audits your assets (Images, Videos, Vectors) against Adobe Stock, Shutterstock, & Freepik curator standards before submission.\n\n📌 What Does Quality Check Analyze?\n\n1. 🎯 YOLO Instance Segmentation & Bounding Box Overlays:\n• Real-Time Object Isolation: Detects pixel-level object boundaries, alpha edge fringing, halo artifacts, and cutout cleanliness.\n• Interactive Bounding Box Heatmap: Pinpoints exact defect coordinates with color-coded YOLO boxes (Logos, AI anomalies, noise, blur, cut-off subjects).\n• Foreground/Background Depth Separation: Confirms main subjects remain in focus while background bokeh remains natural.\n\n2. 🔍 Technical & Pixel Forensic Analysis:\n• Sharpness & Focus: Detects blur, soft focus, and out-of-focus areas on main subjects.\n• Lighting & Exposure: Checks for blown highlights, crushed shadows, and contrast balance.\n• Noise & Compression: Measures sensor noise, grain, JPEG blocking artifacts, and color banding.\n• Resolution & Histogram: Validates commercial resolution, 32-channel luminance spectrum, and file format.\n\n3. ⚖️ IP, Trademark & Legal Detection:\n• Trademarks & Logos: Scans for recognized commercial logos (Apple, Nike, Converse, etc.).\n• Watermarks & Text: Detects watermarks, unwanted text overlays, or agency stamps.\n• Restricted Landmarks & Releases: Flags properties requiring Property or Model Releases.\n\n4. 🤖 AI & Anatomical Integrity Check:\n• AI Anatomical Defects: Detects distorted hands, extra/missing fingers, facial anomalies.\n• Proportion & Structure: Flags weird perspective, warped mechanical parts, and impossible geometry.\n• Gibberish Text: Detects corrupted or meaningless AI-generated text.\n\n5. 📊 Results & Recommendations:\n• Curation Viability Score (0 - 100%) & Status (PASS / FAIL).\n• Interactive Visual Heatmap & YOLO Bounding Boxes highlighting exact problem coordinates.\n• SEO-ready Title and Keywords suggestions with 1-click copy.",
    guide_calendar_title: "Calendar AI Guide",
    guide_calendar_desc: "Generate seasonal stock calendar ideas by inputting a month/event. Never miss a commercial stock trend again.",
    sidebar_mute_video: "Mute Video Gen",
    sidebar_bg_remover: "Background Remover",
    sidebar_motion_gen: "Motion Gen",
    sidebar_anti_spam: "Anti-Spam Similar Checker",
    mute_title: "Batch Mute Video Gen",
    mute_subtitle: "Instantly remove audio from multiple stock videos losslessly at once",
    mute_btn_clear: "Clear All",
    mute_drag_drop: "Drag & drop multiple video files here",
    mute_formats_supported: "Supports multiple MP4, MOV, WebM files (Max 500MB per file)",
    mute_btn_choose: "CHOOSE VIDEO FILES",
    mute_error_invalid_files: "The following files were ignored because they are not videos: {names}",
    mute_queue_title: "Video Queue List ({count})",
    mute_stat_done: "Done",
    mute_stat_processing: "Processing",
    mute_stat_failed: "Failed",
    mute_stat_pending: "Pending",
    mute_btn_processing: "PROCESSING BATCH ({current}/{total})...",
    mute_btn_mute_queue: "MUTE VIDEO QUEUE",
    mute_btn_download_all: "DOWNLOAD ALL ({count})",
    mute_status_muting: "Muting...",
    mute_status_success: "Success",
    mute_status_failed_badge: "Failed",
    mute_status_pending_badge: "Pending",
    mute_tooltip_remove: "Remove from queue",
    mute_preview_title: "Media Preview",
    mute_preview_size: "Size",
    mute_preview_format: "Format",
    mute_preview_error: "Error",
    mute_preview_empty: "Select a video from the queue list to play the preview",
    mute_guide_title: "Usage Guide",
    mute_guide_step1_title: "Choose Files",
    mute_guide_step1_desc: "Drag multiple videos or click the file selector above.",
    mute_guide_step2_title: "Start Process",
    mute_guide_step2_desc: "Click the Mute Video Queue button to remove sound from all videos sequentially.",
    mute_guide_step3_title: "Download Results",
    mute_guide_step3_desc: "Download individually using the button next to the filename, or click Download All to download all successful videos at once.",
    mute_guide_footer: "🔒 All files are processed locally on a secure sandbox server, and will be destroyed immediately after downloading is completed.",
    guide_mute_video_title: "Mute Video Guide",
    guide_mute_video_desc: "Instantly remove audio from multiple stock videos losslessly at once to meet submission requirements.",
    mute_auto_download_label: "Auto-Download",
    mute_auto_download_desc: "Automatically download after processing",
    mute_trial_expired: "⚠️ Daily free trial limit (25 video mutes) reached. Please contact admin or enter activation code for unlimited processing.",
    mute_trial_remaining: "Free trial 25 video mutes/day. Remaining quota today: {remaining} times",
    mute_error_trial: "Trial Limit Exceeded. You have reached the maximum limit of 25 video mutes today. Please contact admin or enter activation code for unlimited processing.",
  },
  id: {
    header_title: "MetaZo PRO",
    main_subtitle_line1: "Asisten Metadata Berbasis AI",
    main_subtitle_line2: "Spesialis Kontributor Adobe Stock, Shutterstock, Freepik, Vecteezy, Canva",
    
    help_button: "Grup WhatsApp & Bantuan",
    donate_button: "Donasi / Dukungan",
    whatsapp_link: "https://chat.whatsapp.com/EJgcCSymQYE3724FqpFzxr", 
    footer_text: "🔐 Dikembangkan dengan dedikasi @2026.",

    image_tool: "Gambar",
    video_tool: "Video",
    vector_tool: "Vektor",
    
    upload_images: "1. Unggah File Gambar",
    upload_videos: "1. Unggah File Video",
    upload_vector_thumbnails: "1. Unggah File Vektor",
    drag_drop: "Tarik & lepas di sini, atau",
    click_to_choose: "pilih file",
    files_selected: "file terpilih.",
    uploading_file: "Mempersiapkan unggahan...",
    add_new: "Tambah Lagi",
    clear_all: "Hapus Semua",

    generate_metadata_ai: "2. Optimasi Metadata AI",
    generate_desc: "AI menganalisis konten visual (termasuk multi-frame untuk video) untuk hasil terbaik.",
    continue_generate: "Lanjutkan Proses",
    custom_prompt_optional: "Instruksi / Target Kata Kunci (Opsional):",
    custom_prompt_placeholder: "Contoh: 'gaya retro, fokus pada syal merah' atau 'Biru, Laut, Musim Panas'.",
    keyword_count_label: "Jumlah Kata Kunci (1-49):",
    keyword_count_auto: "Otomatis",
    generate_all: "Proses Metadata",
    generating: "AI sedang menganalisis...",
    retry_failed: "Coba Ulang Gagal",
    ai_processing: "Proses AI sedang berlangsung...",
    generation_mode_label: "Mode Pemrosesan:",
    generation_mode_standard: "Standar",
    generation_mode_standard_desc: "Akurat, stabil.",
    generation_mode_batch: "Batch",
    generation_mode_batch_desc: "Cepat, pemrosesan serentak.",

    review_edit: "3. Tinjau & Edit",
    review_edit_desc: "Verifikasi kepatuhan terhadap standar stock melalui kotak pratinjau.",
    keywords_label: "Kata Kunci",
    title_label: "Judul",
    description_label: "Deskripsi",
    category_adobe_label: "Kategori Adobe Stock",
    category_shutterstock_1_label: "Kategori Shutterstock 1",
    category_shutterstock_2_label: "Kategori Shutterstock 2",
    enter_title: "Masukkan judul...",
    enter_description: "Deskripsikan konten...",
    select_category: "Pilih kategori...",
    original_filename: "Nama File:",
    close: "Tutup",
    download_csv: "Unduh CSV",
    download_disabled_tooltip: "Selesaikan semua proses AI terlebih dahulu.",
    export_metadata: "4. Ekspor",
    language: "Bahasa",
    english: "Inggris",
    indonesian: "Indonesia",
    regenerate: "Regenerasi Metadata",
    hero_badge: "AI-Driven Metadata Engine",
    hero_title_part1: "Optimalisasi",
    hero_title_part2: "Stock Asset",
    hero_title_part3: "Instan",
    hero_description: "MetaZo memanfaatkan kecerdasan AI untuk menghasilkan judul, deskripsi, dan tag otomatis bagi portal stock global.",
    hero_cta_how: "Cara Pakai",
    hero_stats_file: "File",
    license_active_title: "Lisensi Komersial Aktif",
    license_active_desc: "Akses tanpa batas telah aktif untuk workflow profesional",
    license_pro_badge: "★ PRO",
    trial_badge: "Versi Trial",
    trial_desc_part1: "Gunakan",
    trial_desc_part2: "dalam mode terbatas. Dapatkan akses unlimited dengan lisensi premium seharga",
    trial_cta_license: "Lisensi",
    trial_cta_admin: "Admin",
    workspace_title: "Pilih Ruang Kerja",
    workspace_modes: "3 Mode",
    image_ws_title: "Image AI",
    image_ws_desc: "Optimasi foto, poster, atau karya seni raster (JPG, PNG, WEBP) secara otomatis.",
    image_ws_cta: "Optimasi Gambar",
    video_ws_title: "Video AI",
    video_ws_desc: "Analisis klip video (MP4, MOV, WEBM) untuk metadata sinematik yang presisi.",
    video_ws_cta: "Optimasi Video",
    vector_ws_title: "Vector AI",
    vector_ws_desc: "Metadata otomatis untuk file vektor (SVG, EPS, AI) guna kebutuhan elemen desain UI/UX.",
    vector_ws_cta: "Optimasi Vektor",
    daily_quota: "Kuota Hari Ini",
    quota_exhausted: "⚠️ Kuota habis. Coba besok.",
    queue_status_title: "Status Antrean Data",
    status_success: "Metadata Oke",
    status_ready: "Siap Diproses AI",
    status_draft: "Draf Belum Dikonfigurasi",
    status_error: "Masalah / Error",
    success_rate: "Persentase Sukses",
    dist_title: "Distribusi Format Upload",
    no_files_title: "Belum Ada File Terunggah",
    no_files_desc: "Gunakan tab menu \"Metadata Gen\" untuk mengunggah file Anda.",
    dist_image_label: "Ruang Kerja Gambar (Image)",
    dist_video_label: "Ruang Kerja Video (Video)",
    dist_vector_label: "Ruang Kerja Vektor (Vector)",
    portal_ready: "Siap",
    sidebar_dashboard: "Dashboard",
    sidebar_metadata_gen: "Gen Metadata",
    sidebar_prompt_gen: "Gen Prompt",
    sidebar_prompt_text: "Prompt Teks",
    sidebar_prompt_image: "Prompt Gambar",
    sidebar_prompt_video: "Prompt Video",
    sidebar_image_check: "Kurator Adobe Cek",
    sidebar_video_check: "Cek Kualitas Video",
    sidebar_calendar_gen: "Gen Kalender",
    sidebar_ftp_uploader: "FTP Stock Uploader",
    sidebar_chat: "Chat Akun",
    sidebar_activation_premium: "AKTIVASI PREMIUM",
    sidebar_pro_active: "PRO AKTIF",
    sidebar_manage: "Kelola",
    sidebar_core_generators: "Generator Utama",
    sidebar_core_tools: "Alat Utama",
    sidebar_processing_mode: "Mode Proses",
    sidebar_tuning: "Tuning",
    sidebar_resources: "Sumber Daya",
    sidebar_about: "Tentang MetaZo PRO",
    sidebar_subscription_plan: "Paket Langganan",
    default_pricing: "30 Hari = 50.000 - Unlimited = 250.000",
    topbar_system_time: "Waktu Sistem Saat Ini",
    topbar_stability_core: "STABILITAS CORE AKTIF",
    topbar_pro_active: "👑 PRO AKTIF",
    topbar_trial_eval: "⚠️ EVALUASI TRIAL",
    upload_title: "Unggah Aset",
    upload_reset: "Atur Ulang",
    upload_reset_title: "Atur Ulang Semua",
    upload_help: "Unggah file gambar, video, atau vektor Anda di sini untuk diproses.",
    upload_file_placeholder: "FILE",
    upload_next_ai: "Lanjut: Konfigurasi AI",
    info_modal_title: "MetaZo PRO Handbook & Petunjuk Penggunaan",
    info_modal_operational_guide: "✨ Panduan Operasional MetaZo PRO",
    info_modal_step1_title: "Workspace Selection",
    info_modal_step1_desc_p1: "Pilih mode",
    info_modal_step1_desc_p2: "pada Dashboard utama. Unggah file Anda melalui fitur drag-and-drop atau klik area unggah.",
    info_modal_step2_title: "AI Analysis & Metadata Generation",
    info_modal_step2_desc: "Setelah diunggah, klik Process Metadata. Mesin AI Vision kami akan menganalisis konten visual untuk menghasilkan Judul, Deskripsi, dan Kategori secara otomatis.",
    info_modal_step3_title: "Prompt Gen & Image AI (Terintegrasi!)",
    info_modal_step3_desc_highlight: "Fitur Prompt Gen kini terintegrasi dengan Calendar Gen untuk memudahkan pembuatan konten stok berdasarkan event terpopuler.",
    info_modal_step3_desc_main: "Gunakan fitur Prompt Gen untuk menghasilkan deskripsi visual yang mendalam untuk AI Art.",
    info_modal_step4_title: "Image Check (QC)",
    info_modal_step4_desc: "Pastikan aset Anda bebas dari pelanggaran IP, logo, dan noise berlebih dengan fitur Image Check sebelum diunggah ke agency.",
    info_modal_step5_title: "Calendar Gen (Niche Hunter)",
    info_modal_step5_desc: "Temukan event-event penting di masa depan secara global untuk membantu Anda menentukan tema produksi konten stok yang sedang dicari buyer.",
    info_modal_step6_title: "Export & Download",
    info_modal_step6_desc: "Setelah sesuai, gunakan fitur Export untuk mengunduh metadata dalam format CSV yang kompatibel dengan Adobe Stock, Shutterstock, dll.",
    info_modal_tips_title: "⚡ Tips Mode Pemrosesan",
    info_modal_std_mode_title: "Standard Mode",
    info_modal_std_mode_desc: "Memproses file satu per satu secara berurutan. Sangat aman dan stabil untuk menghindari kendala batasan API (rate limit).",
    info_modal_batch_mode_title: "Batch Mode",
    info_modal_batch_mode_desc: "Memproses banyak file sekaligus secara simultan. Disarankan untuk memproses asset dalam jumlah besar jika waktu menjadi prioritas utama Anda.",
    info_modal_trial_premium_title: "💳 Handbook Trial & Premium",
    info_modal_trial_mode_label: "Mode Trial:",
    info_modal_trial_mode_desc: "Anda berada dalam masa uji coba gratis dengan batasan harian untuk memastikan kestabilan sistem. Fitur tertentu mungkin terbatas.",
    info_modal_premium_mode_label: "Premium (Lisensi):",
    info_modal_premium_mode_desc: "Dengan Serial Key lisensi, semua batasan dihapus sepenuhnya. Dapatkan akses unlimited untuk pemrosesan aset profesional Anda.",
    info_modal_license_cta: "Butuh lisensi? Hubungi admin untuk mendapatkan Serial Key resmi & tingkatkan akun Anda ke Premium!",
    info_modal_supported_formats: "📁 Format File yang Didukung",
    info_modal_close_button: "Tutup Petunjuk",
    settings_modal_title: "Pengaturan Provider Model AI",
    settings_main_provider_label: "Provider AI Utama Yang Digunakan",
    settings_gemini_model_label: "Pilih Model Gemini",
    settings_gemini_desc: "Anda dapat menyimpan beberapa API Key Gemini pribadi. Sistem secara cerdas melakukan rotasi otomatis demi menghindari hambatan kuota (*rate limit / RESOURCE_EXHAUSTED*).",
    settings_gemini_key_list: "Daftar API Key Gemini",
    settings_no_keys: "Tidak ada API Key yang ditemukan untuk provider ini.",
    settings_gemini_model_auto: "Otomatis (Pilih Yang Stabil)",
    settings_use_default_key: "Menggunakan Gemini Key default server global.",
    welcome_title: "Selamat Datang di MetaZo PRO v1.3.0",
    welcome_subtitle: "Stock Asset Optimizer",
    welcome_features_label: "Fitur:",
    welcome_feature1: "Optimasi aset stok bertenaga AI",
    welcome_feature2: "Generasi ringan & cepat",
    welcome_feature3: "Dukungan banyak provider",
    welcome_feature4: "Manajemen prompt lanjutan",
    welcome_get_started: "Mulai Sekarang",
    common_or: "atau",
    common_and: "dan",
    activation_modal_title_trial_expired: "Masa Trial Habis",
    activation_modal_title_normal: "Aktivasi Lisensi Resmi",
    activation_modal_unlock_premium: "Unlock Premium SaaS",
    activation_active_status: "Aplikasi Aktif • Premium PRO",
    activation_key_registered: "Kunci Terdaftar:",
    activation_subscription_left: "Masa Berlangganan:",
    activation_days_left: "Hari Lagi",
    activation_commercial_notice: "Commercial copy licensed under key constraints.",
    activation_btn_unsubscribe: "Berhenti Berlangganan (Cabut Lisensi)",
    activation_trial_expired_hero: "Masa Trial 7 Hari Habis!",
    activation_trial_expired_desc: "Masa uji coba gratis Anda telah berakhir. Sila lakukan pembayaran dan masukkan Serial Key Lisensi di bawah untuk melanjutkan pemakaian Metadata Gen, Prompt Teks, & Kalender Gen.",
    activation_trial_active_hero: "Masa Trial Aktif",
    activation_trial_active_days: "Hari Lagi",
    activation_trial_active_desc: `Anda berada di mode Free Trial. Semua fitur terbuka dengan batasan maksimal ${getDailyLimit()} kali generate per hari. Lakukan aktivasi resmi untuk membuka semua fitur tanpa batas.`,
    activation_input_label: "Masukkan Serial Key Lisensi",
    activation_input_placeholder: "FORMAT: MZPRO-XXXX-XXXX-XXXX",
    activation_error_empty: "Mohon masukkan Serial Key lisensi Anda terlebih dahulu.",
    activation_error_expired: "Masa aktif Serial Key ini (30 Hari) telah kedaluwarsa. Sila beli key baru.",
    activation_error_used: "Serial Key ini sudah digunakan oleh pengguna lain! Mohon gunakan Serial Key yang berbeda.",
    activation_error_invalid: "Serial Key tidak terdaftar atau salah. Sila hubungi Admin untuk membeli Key Resmi.",
    activation_error_offline: "Koneksi internet bermasalah dan validasi offline gagal.",
    activation_success_waiting: "✔ Lisensi divalidasi! Mengaktifkan premium...",
    activation_btn_process: "Memproses Aktivasi...",
    activation_btn_activate: "Aktivasi Premium",
    activation_no_license_title: "Belum Punya Lisensi? Dapatkan Instan:",
    activation_personal_activation: "Aktivasi Personal",
    activation_license_price: "Harga Lisensi:",
    activation_buy_whatsapp: "Beli Key Lisensi via WhatsApp",
    activation_confirm_stop_title: "Konfirmasi Berhenti",
    activation_confirm_stop_desc: "Apakah Anda yakin ingin mematikan status premium dan mengembalikan aplikasi ke masa uji coba / trial?",
    activation_btn_stop_yes: "Ya, Berhenti",
    activation_btn_stop_no: "Batal",
    sidebar_expand: "Perluas Sidebar",
    sidebar_collapse: "Sembunyikan Sidebar",
    sidebar_manage_license: "Kelola Lisensi / Berhenti Langganan",
    sidebar_activation_tooltip: "Aktivasi Lisensi Resmi / Mulai Pro",
    topbar_toggle_theme: "Ganti Tema",
    topbar_info_manual: "Petunjuk Manual",
    topbar_settings_api: "Pengaturan & API Key",
    common_editor: "Editor",
    common_mode: "Mode",
    prompt_title: "Prompt Teks Studio",
    prompt_subtitle: "Sintesis Ide Visual dengan Spektrum Kreativitas & Kategori Artistik",
    prompt_engine_active: "Gemini Pro Engine Active",
    prompt_formula_title: "Formula & Konfigurasi Estetika",
    prompt_tab_background: "Tab Background",
    prompt_tab_png: "Tab PNG Asset",
    prompt_trial_label: "Trial Hari Ini: Prompt Teks",
    prompt_generate_count: "Generate",
    prompt_trial_expired: `⚠️ Batas trial gratis harian (${getDailyLimit()} generate) telah dicapai. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.`,
    prompt_trial_remaining: `Masa Trial gratis ${getDailyLimit()} generate/hari. Sisa kuota generate hari ini:`,
    prompt_trial_times: "kali",
    prompt_image_trial_label: "Trial Hari Ini: Prompt Gambar",
    prompt_image_generate_count: "Generate",
    prompt_image_trial_expired: `⚠️ Batas trial gratis harian (${getDailyLimit()} generate) telah dicapai. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.`,
    prompt_image_trial_remaining: `Masa Trial gratis ${getDailyLimit()} generate/hari. Sisa kuota generate hari ini:`,
    prompt_image_trial_times: "kali",
    prompt_video_trial_label: "Trial Hari Ini: Prompt Video",
    prompt_video_generate_count: "Generate",
    prompt_video_trial_expired: `⚠️ Batas trial gratis harian (${getDailyLimit()} generate) telah dicapai. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.`,
    prompt_video_trial_remaining: `Masa Trial gratis ${getDailyLimit()} generate/hari. Sisa kuota generate hari ini:`,
    prompt_video_trial_times: "kali",
    image_check_trial_label: "Trial Hari Ini: Audit Kualitas",
    image_check_generate_count: "Audit",
    image_check_trial_expired: `⚠️ Batas trial gratis harian (${getDailyLimit()} audit) telah dicapai. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.`,
    image_check_trial_remaining: `Masa Trial gratis ${getDailyLimit()} audit/hari. Sisa kuota audit hari ini:`,
    image_check_trial_times: "kali",
    prompt_subject_label: "Ide Visual / Subjek Gambar",
    prompt_subject_placeholder: "Ketik ide visual Anda secara bebas di sini...",
    prompt_inspiration_label: "💡 Butuh Inspirasi? Klik Preset di bawah:",
    prompt_negative_label: "Negative Prompt (Anti-Elemen)",
    prompt_negative_subtitle: "Avoid Elements",
    prompt_negative_desc: "Elemen di atas akan dikirimkan ke model AI untuk dihindari secara ketat pada hasil sintesis prompt.",
    prompt_style_master_label: "Kategori Gaya Master (Artistic Master Style)",
    prompt_style_quick_label: "Gaya Cepat (Quick Selection Tab)",
    prompt_png_bg_label: "Pilihan Background PNG",
    prompt_png_bg_desc: "AI secara pintar akan menyematkan instruksi warna latar belakang solid ini ke dalam prompt agar subjek gambar terisolasi dengan rapi.",
    prompt_variation_label: "Dimensi & Jml Variasi Output",
    prompt_variation_unit: "Variasi",
    prompt_word_count_label: "Word Count Range (Panjang Prompt)",
    prompt_word_count_desc: "Mengatur seberapa detail AI mengekspansi deskripsi visual setiap prompt.",
    prompt_btn_synthesize: "Sintesis {count} Prompt Sekarang",
    prompt_btn_synthesizing: "AI Mengekspansi {count} Variasi Estetika...",
    prompt_preset_lite: "Cepat, efisien, formulasi ringkas dan representatif.",
    prompt_preset_artistic: "Penuh opsi atmosfer kamera, lensa variatif, dan gaya estetis seimbang.",
    prompt_preset_ultra: "Detail super kompleks, kaya tekstur, opsi lighting, dan ragam sudut pandang.",
    prompt_loading_step1: "Merumuskan Skenario Kreatif...",
    prompt_loading_step2: "Mensintesis Detail Artistik...",
    prompt_loading_step3: "Memoles Spektrum Prompt...",
    prompt_loading_step4: "Finalisasi Koleksi Output...",
    prompt_studio_title: "Prompt Teks Studio",
    prompt_studio_subtitle: "Sintesis Ide Visual dengan Spektrum Kreativitas & Kategori Artistik",
    prompt_studio_version: "Advanced AI Teks Creator v2.5",
    prompt_output_title: "Generated Prompts",
    prompt_output_subtitle: "Semua prompt siap disalin ke Midjourney / DALL-E / Firefly / Stable Diffusion",
    prompt_output_badge_png: "✨ PNG: LATAR {color}",
    prompt_output_badge_scene: "🖼️ Background Scene",
    prompt_output_btn_copy_all: "Salin Semua",
    prompt_output_btn_copied: "Disalin",
    prompt_output_btn_download: "Download",
    prompt_output_btn_clear: "Clear",
    prompt_output_search_placeholder: "Saring prompt (contoh: 'lighting', 'macro', 'epic', 'camera')...",
    prompt_output_no_match_title: "Tidak ada kecocokan filter",
    prompt_output_no_match_desc: "Kata kunci \"{query}\" tidak ditemukan pada {count} prompt.",
    image_studio_title: "Prompt Image Studio",
    image_studio_subtitle: "Ekstraksi Deskripsi & Estetika dari Referensi Gambar Anda (Single & Batch Mode)",
    image_studio_version: "Image-to-Prompt Batch v2.0",
    image_studio_upload_label: "Panel Unggah Gambar",
    image_studio_clear_all: "Hapus Semua",
    image_studio_drag_drop: "Unggah / Seret Gambar",
    image_studio_release: "Lepaskan Gambar",
    image_studio_support_multiple: "Mendukung banyak file sekaligus",
    image_studio_target_label: "Pilih Target Estetika",
    image_studio_btn_analyze: "Hasilkan Prompt ({count} Item Baru)",
    image_studio_btn_analyzing: "Memproses {count} Item ({progress}%)",
    image_studio_dashboard_title: "Progress Dashboard Antrian",
    image_studio_status_label: "Status: {finished}/{total} Selesai",
    image_studio_btn_copy_all: "Salin Semua",
    image_studio_btn_copied_all: "Disalin Semua",
    image_studio_empty_title: "Belum Ada Gambar dalam Antrian",
    image_studio_empty_desc: "Unggah satu atau beberapa gambar referensi untuk mengekstraksi prompt estetika AI secara instan.",
    
    video_studio_title: "Prompt Video Studio",
    video_studio_subtitle: "Sintesis Deskripsi & Prompt dari Referensi Gerak Video",
    video_studio_keyword_placeholder: "Masukkan keyword gerak (contoh: 'Cinematic Landscape', 'Epic Action')...",
    video_studio_btn_analyze: "Analisis Gerak",
    video_studio_btn_analyzing: "Menganalisis...",
    video_studio_history_title: "Riwayat Analisis",
    video_studio_btn_clear_history: "Bersihkan Riwayat",
    video_studio_hollywood_title: "Sintesis Hollywood",
    video_studio_hollywood_desc: "Hasilkan prompt director standar Hollywood profesional berdasarkan analisis gerak.",
    video_studio_btn_generate_hollywood: "Hasilkan Hollywood Prompt",
    video_studio_btn_generating_hollywood: "Mensintesis Hollywood Prompt...",
    video_studio_btn_download: "Download Prompt",
    video_studio_camera_label: "Kamera",
    video_studio_technical_label: "Technical String",
    video_studio_saturation_title: "Saturasi Pasar",
    video_studio_saturation_desc: "Peringatan otomatis jika pasar sudah terlalu jenuh dengan konten serupa.",
    video_studio_revenue_title: "Prakiraan Pendapatan",
    video_studio_revenue_desc: "Estimasi potensi pendapatan berdasarkan tren pembeli di Adobe Stock & Shutterstock.",
    video_studio_error_empty: "Mohon masukkan keyword terlebih dahulu.",
    video_studio_error_fail: "Gagal menganalisis keyword. Coba lagi nanti.",
    calendar_title: "Kalender Visual Strategis",
    calendar_subtitle: "Temukan momen strategis berdasarkan hari libur & tren pasar global.",
    calendar_months_january: "Januari",
    calendar_months_february: "Februari",
    calendar_months_march: "Maret",
    calendar_months_april: "April",
    calendar_months_may: "Mei",
    calendar_months_june: "Juni",
    calendar_months_july: "Juli",
    calendar_months_august: "Agustus",
    calendar_months_september: "September",
    calendar_months_october: "Oktober",
    calendar_months_november: "November",
    calendar_months_december: "Desember",
    calendar_btn_generate: "Cari Event",
    calendar_btn_generating: "Menganalisis...",
    calendar_month_label: "Pilih Bulan",
    calendar_card_btn_keywords: "Hasilkan Keyword",
    calendar_card_btn_prompt: "Buat Prompt",
    calendar_error_fail: "Gagal memuat event. Silakan coba lagi.",

    style_photorealistic: "Photorealistic (Realistis)",
    style_cinematic: "Cinematic (Film)",
    style_adobe_stock: "Adobe Stock Style",
    style_editorial: "Editorial (Majalah)",
    style_lifestyle: "Lifestyle (Gaya Hidup)",
    style_fine_art: "Fine Art (Seni Tinggi)",
    prompt_error_trial: `Batas Trial Terlampaui. Anda telah mencapai batas maksimal ${getDailyLimit()} kali generate Prompt Teks hari ini. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.`,
    prompt_error_empty: "Silakan masukkan ide dasar atau subjek murni visual terlebih dahulu.",
    prompt_png_bg_white: "⚪ Latar Putih (White background)",
    prompt_png_bg_black: "⚫ Latar Hitam (Black background)",
    prompt_png_bg_transparent: "🏁 Latar Transparan (Transparent background)",
    qc_title: "Audit",
    qc_title_check: "Kualitas",
    qc_subtitle: "AI Expert Standar Adobe Stock",
    qc_btn_reset: "Reset",
    qc_btn_analyze: "Mulai Audit Asset",
    qc_btn_analyzing: "Menganalisis...",
    qc_tolerance_label: "Toleransi Kualitas",
    qc_upload_hub: "Upload Hub",
    qc_drop_images_here: "Drop Gambar/Video/Vektor Di Sini",
    qc_release_images: "Lepaskan File",
    qc_multiple_upload: "Mendukung Gambar, Video & Vektor (.eps, .ai)",
    qc_queue_assets: "Asset dalam Antrean",
    qc_pending_audit: "Menunggu Audit",
    qc_analyzing_text: "Spesialis QC Adobe Stock",
    qc_analyzing_desc: "Menganalisis nilai hukum, teknis, dan komersial",
    qc_info_empty: "Silahkan upload file dulu untuk memulai proses audit kurasi",
    qc_score_label: "SKOR QC",
    qc_hide_heatmap: "Sembunyikan Heatmap",
    qc_analyze_heatmap: "Analisis Heatmap Pixel",
    qc_pixel_engine: "Pixel Engine",
    qc_rejection_reason: "Alasan Penolakan",
    qc_legal_status: "Status Hukum",
    qc_quality_metadata: "Metadata Kualitas",
    qc_close: "Tutup",
    qc_view_audit: "Lihat Audit",
    qc_strengths: "Kelebihan",
    qc_tech_analysis: "Analisis Teknis",
    qc_detailed_feedback: "Umpan Balik Detail",
    
    guide_btn_title: "Lihat Panduan Fitur",
    guide_dashboard_title: "Panduan Dashboard",
    guide_dashboard_desc: "Ringkasan metrik akun, utilitas dan akses langsung ke seluruh alat asisten metadata Anda.",
    guide_prompt_gen_title: "Panduan Prompt Studio",
    guide_prompt_gen_desc: "Fitur Prompt Teks membantu Anda meracik formula prompt profesional berstandar tinggi untuk AI Generator (Midjourney, DALL-E 3, Stable Diffusion, Recraft, Flux, dll.).\n\n📌 Panduan Lengkap Fitur Prompt Teks:\n\n1. 📝 Input Subjek & Ide Acak (Auto Subject):\n• Ketik kata kunci, tema, atau subjek yang ingin dibuat (contoh: \"cyberpunk barista robot\", \"cozy winter coffee shop\").\n• Bingung mencari ide? Klik tombol \"✨ Ide Subjek Acak\" untuk menghasilkan ide konsep komersial yang unik dan trendi secara otomatis.\n\n2. 🎭 Mode Format (Background vs Objek PNG):\n• Mode Background: Menghasilkan gambar pemandangan, lanskap, wallpaper, atau komposisi penuh dengan latar belakang dinamis.\n• Mode Objek PNG (Isolated): Mengisolasi objek utama pada latar belakang solid (Putih / Hitam / Transparan) agar mudah dipotong dan dijual sebagai aset elemen desain.\n\n3. 🎨 Pilihan Kategori Gaya & Sub-Style:\n• Pilih dari 20+ preset gaya visual populer (Flat Illustration, 3D CGI, Cinematic, Photorealistic, Vector Art, Watercolor, Cyberpunk, Anime, Graphic Design, dll.).\n• Untuk gaya tertentu (seperti Flat Vector atau Dark Horror), Anda dapat memilih Sub-Style lanjutan seperti Minimal Flat, Corporate Alegria, Isometric, atau Gothic Horror.\n\n4. ⚙️ Jumlah Variasi & Negative Prompt:\n• Slider Variasi (5 - 15): Tentukan berapa banyak variasi prompt unik yang ingin diracik sekaligus.\n• Negative Prompt: Masukkan kata-kata atau elemen yang ingin dicegah muncul pada hasil gambar (contoh: \"blurry, text, watermark, bad anatomy\").\n\n5. 📋 Salin & Ekspor:\n• Salin prompt satu per satu dengan tombol Salin (Copy), atau gunakan \"Salin Semua\" untuk langsung mengekspor seluruh variasi prompt ke clipboard Anda.",
    guide_prompt_text_title: "Panduan Prompt Teks",
    guide_prompt_text_desc: "Fitur Prompt Teks membantu Anda meracik formula prompt profesional berstandar tinggi untuk AI Generator (Midjourney, DALL-E 3, Stable Diffusion, Recraft, Flux, dll.).\n\n📌 Panduan Lengkap Fitur Prompt Teks:\n\n1. 📝 Input Subjek & Ide Acak (Auto Subject):\n• Ketik kata kunci, tema, atau subjek yang ingin dibuat (contoh: \"cyberpunk barista robot\", \"cozy winter coffee shop\").\n• Bingung mencari ide? Klik tombol \"✨ Ide Subjek Acak\" untuk menghasilkan ide konsep komersial yang unik dan trendi secara otomatis.\n\n2. 🎭 Mode Format (Background vs Objek PNG):\n• Mode Background: Menghasilkan gambar pemandangan, lanskap, wallpaper, atau komposisi penuh dengan latar belakang dinamis.\n• Mode Objek PNG (Isolated): Mengisolasi objek utama pada latar belakang solid (Putih / Hitam / Transparan) agar mudah dipotong dan dijual sebagai aset elemen desain.\n\n3. 🎨 Pilihan Kategori Gaya & Sub-Style:\n• Pilih dari 20+ preset gaya visual populer (Flat Illustration, 3D CGI, Cinematic, Photorealistic, Vector Art, Watercolor, Cyberpunk, Anime, Graphic Design, dll.).\n• Untuk gaya tertentu (seperti Flat Vector atau Dark Horror), Anda dapat memilih Sub-Style lanjutan seperti Minimal Flat, Corporate Alegria, Isometric, atau Gothic Horror.\n\n4. ⚙️ Jumlah Variasi & Negative Prompt:\n• Slider Variasi (5 - 15): Tentukan berapa banyak variasi prompt unik yang ingin diracik sekaligus.\n• Negative Prompt: Masukkan kata-kata atau elemen yang ingin dicegah muncul pada hasil gambar (contoh: \"blurry, text, watermark, bad anatomy\").\n\n5. 📋 Salin & Ekspor:\n• Salin prompt satu per satu dengan tombol Salin (Copy), atau gunakan \"Salin Semua\" untuk langsung mengekspor seluruh variasi prompt ke clipboard Anda.",
    guide_prompt_image_title: "Panduan Prompt Gambar",
    guide_prompt_image_desc: "Unggah gambar referensi untuk mengekstraksi deskripsi estetika dan formula prompt secara instan.\n\n📌 Panduan Fitur Prompt Image:\n1. Penggunaan Tombol Paste (Ctrl+V):\n• Salin gambar dari web manapun (klik kanan > Salin Gambar / Copy Image) atau screenshot (Win + Shift + S), lalu klik tombol \"Salin Tempel (Ctrl+V)\" atau tekan Ctrl+V di keyboard untuk langsung memproses tanpa perlu mendownload file gambar terlebih dahulu.\n\n2. Jumlah Variasi Prompt:\n• Atur slider (5 - 15 variasi) untuk menentukan berapa banyak variasi prompt unik yang ingin dihasilkan dari satu gambar referensi.\n\n3. Centang \"Tanpa Style\":\n• Aktifkan opsi \"Tanpa Style\" agar AI secara otomatis mendeteksi dan mengikuti medium & gaya estetika asli dari gambar referensi tanpa dipaksa ke preset style tertentu.",
    guide_prompt_video_title: "Panduan Prompt Video",
    guide_prompt_video_desc: "Analisis kata kunci gerakan untuk mensintesis prompt sinematik dan instruksi direktur secara profesional.",
    guide_image_title: "Panduan AI Gambar",
    guide_image_desc: "Deskripsi otomatis gambar Anda menjadi metadata standar tinggi (Judul, Deskripsi, 50 Keywords komersial).",
    guide_video_title: "Panduan AI Video",
    guide_video_desc: "Dapatkan kata kunci khusus footages yang mengekstrak elemen gerakan, sinematografi, dan alur.",
    guide_vector_title: "Panduan Vektor EPS",
    guide_vector_desc: "Unggah fle EPS ilustrasi secara langsung. Sistem akan dengan mulus mengekstrak metadata spesifik grafik vektor.",
    guide_image_check_title: "Panduan Quality Check",
    guide_image_check_desc: "Fitur Quality Check memindai dan mengaudit aset (Gambar, Video, Vektor) secara otomatis dengan standar kurator Adobe Stock, Shutterstock, & Freepik sebelum Anda submit.\n\n📌 Apa Saja yang Dianalisis oleh Quality Check?\n\n1. 🎯 YOLO Instance Segmentation & Bounding Box Overlay:\n• Isolasi Objek & Tepi Alpha: Mendeteksi kebersihan pinggiran objek transparan (PNG), halo effect, dan artefak potongan gambar.\n• Bounding Box Forensik Interaktif: Menandai titik cacat dengan kotak koordinat dan label presisi (Logo brand, cacat anatomi AI, blur, objek terpotong).\n• Pemisahan Foreground/Background: Memastikan subjek utama tajam dan fokus alami.\n\n2. 🔍 Analisis Teknis & Forensik Piksel:\n• Ketajaman & Fokus: Deteksi blur, soft focus, dan out-of-focus pada objek utama.\n• Pencahayaan & Kontras: Memeriksa overexposure (blown highlights) dan underexposure (crushed shadows).\n• Noise & Kompresi: Mengukur tingkat noise sensor, grain, artefak JPEG blocking, dan color banding.\n• Resolusi & Histogram: Cek resolusi komersial, spektrum luminansi 32-channel, dan format file.\n\n3. ⚖️ Deteksi Hukum, Merek & Hak Cipta (IP):\n• Merek Dagang & Logo: Memindai logo brand terkenal (Apple, Nike, Converse, dll.).\n• Watermark & Teks: Mendeteksi watermark, teks liar, atau cap agensi.\n• Landmark & Properti Terbatas: Deteksi objek/arsitektur yang membutuhkan Property Release atau Model Release.\n\n4. 🤖 Integritas Anatomi & AI Artifact:\n• Cacat Anatomi AI: Mendeteksi jari ekstra/hilang, tangan cacat, dan distorsi wajah hasil AI.\n• Proporsi & Struktur: Memeriksa distorsi mekanis, perspektif ganjil, dan sambungan objek yang tidak logis.\n• Teks Gibberish: Mendeteksi teks cacat/tanpa makna hasil generatif AI.\n\n5. 📊 Hasil & Rekomendasi:\n• Skor Kelayakan Kurasi (0 - 100%) & Keputusan (PASS / FAIL).\n• Heatmap & YOLO Bounding Box Interaktif yang menandai titik masalah pada gambar.\n• Rekomendasi Judul & 50 Kata Kunci (Keywords) SEO siap salin.",
    guide_calendar_title: "Panduan Kalender AI",
    guide_calendar_desc: "Bangun perencanan konten dengan ide-ide komersial musiman yang akan laris berdasarkan tren.",
    sidebar_mute_video: "Mute Video Gen",
    sidebar_bg_remover: "Background Remover",
    sidebar_motion_gen: "Motion Gen",
    sidebar_anti_spam: "Anti-Spam Konten Mirip",
    mute_title: "Batch Mute Video Gen",
    mute_subtitle: "Hilangkan suara dari banyak berkas video stock secara instan & lossless sekaligus",
    mute_btn_clear: "Hapus Semua",
    mute_drag_drop: "Tarik & Letakkan beberapa file video di sini",
    mute_formats_supported: "Mendukung banyak file MP4, MOV, WebM sekaligus (Maks 500MB per file)",
    mute_btn_choose: "PILIH BERKAS VIDEO",
    mute_error_invalid_files: "File berikut diabaikan karena bukan video: {names}",
    mute_queue_title: "Daftar Antrean Video ({count})",
    mute_stat_done: "Selesai",
    mute_stat_processing: "Proses",
    mute_stat_failed: "Gagal",
    mute_stat_pending: "Menunggu",
    mute_btn_processing: "MEMPROSES BATCH ({current}/{total})...",
    mute_btn_mute_queue: "MUTE ANTRIAN VIDEO",
    mute_btn_download_all: "UNDUH SEMUA ({count})",
    mute_status_muting: "Muting...",
    mute_status_success: "Sukses",
    mute_status_failed_badge: "Gagal",
    mute_status_pending_badge: "Menunggu",
    mute_tooltip_remove: "Hapus dari antrean",
    mute_preview_title: "Pratinjau Media",
    mute_preview_size: "Ukuran",
    mute_preview_format: "Format",
    mute_preview_error: "Kesalahan",
    mute_preview_empty: "Pilih video dari daftar antrean untuk memutar pratinjau",
    mute_guide_title: "Panduan Penggunaan",
    mute_guide_step1_title: "Pilih Berkas",
    mute_guide_step1_desc: "Seret beberapa video atau klik tombol pilih berkas di atas.",
    mute_guide_step2_title: "Mulai Proses",
    mute_guide_step2_desc: "Klik tombol Mute Antrian Video untuk menghilangkan suara semua video sekaligus secara berurutan.",
    mute_guide_step3_title: "Unduh Hasil",
    mute_guide_step3_desc: "Unduh satu per satu menggunakan tombol di samping nama file, atau klik Unduh Semua untuk mengunduh semua video sukses sekaligus.",
    mute_guide_footer: "🔒 Semua file diproses secara lokal di server sandbox yang aman, dan akan segera dihancurkan setelah pengunduhan selesai.",
    guide_mute_video_title: "Panduan Mute Video",
    guide_mute_video_desc: "Hilangkan suara dari banyak berkas video stock secara instan & lossless sekaligus untuk memenuhi persyaratan agensi.",
    mute_auto_download_label: "Auto-Unduh",
    mute_auto_download_desc: "Unduh otomatis saat selesai",
    mute_trial_expired: "⚠️ Batas trial gratis harian (25 video mute) telah dicapai. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.",
    mute_trial_remaining: "Masa Trial gratis 25 video mute/hari. Sisa kuota hari ini: {remaining} kali",
    mute_error_trial: "Batas Trial Terlampaui. Anda telah mencapai batas maksimal 25 video mute hari ini. Sila hubungi admin atau masukkan kode aktivasi untuk memproses tanpa batas.",
  }
};

export const DREAMSTIME_CATEGORIES = ['Abstract', 'Animals', 'Arts & Architecture', 'Business', 'Editorial', 'Holidays', 'IT & C', 'Illustrations & Clipart', 'Industries', 'Nature', 'Objects', 'People', 'Technology', 'Web Design'];
export const MIRICANVAS_CATEGORIES = ['Background', 'Frame', 'Object', 'Icon', 'Line', 'Photo', 'Text', 'Template'];
